apiVersion: v2
publisher: radon
name: radon-cicd-plugin
version: 0.0.1
type: VS Code extension
displayName: RADON-h2020 CI/CD plugin
title: RADON CI/CD plugin
description: A plugin to configure and trigger a CI/CD pipeline in a Jenkins server
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/radon-h2020/radon-plugin-registry
category: Other
spec:
  extensions:
    - https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-cicd-plugin/0.0.1/radon-cicd-plugin-0.0.1.vsix